name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Har kuni tunda ishlaydi
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
